### ISSUE TITLE
Running Docker No game list

### ISSUE THREAD

**Issue by Uplinkpro** [DoganM95/PPSSPP-Remote-Disc-Server#7]
Setup the docker on my Unraid box seems to be running a server but nothing is going on, is there any way to test if its running properly? When I add the server to ppsspp it just infinitely says loading game list

**Comment by DoganM95** [comment]
The loading time depends alot on your hardware. However, here is how to check if it is serving properly:  
  
Open a chrome tab, navigate to your server's ip and the port you assigned in the docker run command using `-p`, e.g. `192.168.0.40:15000`. Then open chrome dev tools, go to the network tab reload the page and click the first request. the response status should be `200` and the response body should be a list of all the games, that exist in the directory you bound to the container as a volume, e.g. `-v "/root/games/psp/isos:var/isos"`.  
   
If that works fine, the container is doing what it should and you should check your network as well as hardware performance on both your host and your client.
